import { useState } from 'react';
import { useParams, useOutletContext, Link } from 'react-router-dom';
import { ArrowLeft, Download, CheckCircle2, Cpu, Shield, Leaf, ExternalLink } from 'lucide-react';
import RiskBadge from '../components/RiskBadge';
import StatusPill from '../components/StatusPill';
import StageTimeline from '../components/StageTimeline';
import EmptyState from '../components/EmptyState';
import RoleGuard from '../components/RoleGuard';
import studiesData from '../data/studies.json';
import lifecycleData from '../data/lifecycle.json';
import type { Study } from '../lib/types';
import { formatDate, pct } from '../lib/format';
import clsx from 'clsx';

const MOCK_DEFINE_XML = `<?xml version="1.0" encoding="UTF-8"?>
<!-- VedaConnect AIIA CTMS — CDISC Define-XML 2.1 (DEMO) -->
<!-- Synthetic data only — DPDP Act 2023 compliant prototype -->
<ODM xmlns="http://www.cdisc.org/ns/odm/v1.3" ODMVersion="1.3.2">
  <Study OID="AYU-003">
    <GlobalVariables>
      <StudyName>Guduchi-Pippali Rasayana in Recurrent Respiratory Infections</StudyName>
      <StudyDescription>Phase III Multicentre Ayurveda RCT</StudyDescription>
      <ProtocolName>AIIA-AYU-003-2026</ProtocolName>
    </GlobalVariables>
    <!-- SDTM Domains: DM, AE, DS, SV generated -->
    <!-- Domain: DM (Demographics) -->
    <ItemGroupDef OID="IG.DM" Name="DM" Repeating="No" IsReferenceData="No" SASDatasetName="DM" Domain="DM" Purpose="Tabulation">
      <ItemRef ItemOID="IT.DM.STUDYID" OrderNumber="1" Mandatory="Yes"/>
      <ItemRef ItemOID="IT.DM.USUBJID" OrderNumber="2" Mandatory="Yes"/>
      <ItemRef ItemOID="IT.DM.SUBJID"  OrderNumber="3" Mandatory="Yes"/>
    </ItemGroupDef>
    <!-- Domain: AE (Adverse Events) -->
    <ItemGroupDef OID="IG.AE" Name="AE" Repeating="Yes" IsReferenceData="No" SASDatasetName="AE" Domain="AE" Purpose="Tabulation">
      <ItemRef ItemOID="IT.AE.AETERM"  OrderNumber="1" Mandatory="Yes"/>
      <ItemRef ItemOID="IT.AE.AEDECOD" OrderNumber="2" Mandatory="Yes"/>
      <ItemRef ItemOID="IT.AE.AESOC"   OrderNumber="3" Mandatory="Yes"/>
      <ItemRef ItemOID="IT.AE.AESER"   OrderNumber="4" Mandatory="Yes"/>
    </ItemGroupDef>
    <!-- Generated by VedaConnect CDISC Auto-Engine (demo) -->
    <!-- SDTM + ADaM + Define-XML metadata — no third-party SAS license required -->
  </Study>
</ODM>`;

export default function StudyDetail() {
  const { id } = useParams<{ id: string }>();
  const { currentRole } = useOutletContext<{ currentRole: string }>();
  const [exportProgress, setExportProgress] = useState(0);
  const [exporting, setExporting] = useState(false);
  const [toastMsg, setToastMsg] = useState('');

  const study = (studiesData.studies as Study[]).find(s => s.id === id);

  const handleExportCdisc = () => {
    setExporting(true);
    setExportProgress(0);
    let p = 0;
    const interval = setInterval(() => {
      p += Math.random() * 25 + 10;
      if (p >= 100) {
        p = 100;
        clearInterval(interval);
        setExporting(false);
        // Download
        const blob = new Blob([MOCK_DEFINE_XML], { type: 'application/xml' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `define-${id ?? 'study'}.xml`;
        a.click();
        URL.revokeObjectURL(url);
        setToastMsg('SDTM domains DM, AE, DS, SV + Define-XML metadata generated (demo)');
        setTimeout(() => setToastMsg(''), 5000);
      }
      setExportProgress(Math.min(p, 100));
    }, 300);
  };

  if (!study) return (
    <div className="py-16">
      <EmptyState title="Study not found" description={`No study with ID "${id}" exists in the system.`} />
      <div className="text-center mt-4">
        <Link to="/" className="text-brand text-sm font-medium hover:underline">← Back to Dashboard</Link>
      </div>
    </div>
  );

  const enrollPct = pct(study.enrolled, study.target);
  const stages = lifecycleData.stages;

  return (
    <RoleGuard currentRole={currentRole} pageKey="study">
      <div className="space-y-6 max-w-5xl mx-auto">
        {/* Back link */}
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-ink-mute hover:text-brand transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Dashboard
        </Link>

        {/* Study header card */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
          <div className="bg-gradient-to-r from-ink to-ink-soft px-6 py-6">
            <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-sm font-bold text-brand bg-brand/20 px-2 py-0.5 rounded">{study.id}</span>
                  <span className="text-xs text-white/50">{study.phase}</span>
                </div>
                <h1 className="text-xl font-bold text-white leading-tight">{study.title}</h1>
                <p className="text-sm text-white/60 mt-1">PI: {study.principalInvestigator}</p>
              </div>
              <div className="flex flex-col gap-2 sm:items-end">
                <StatusPill status={study.status} />
                <RiskBadge score={study.riskScore} />
              </div>
            </div>
          </div>
          <div className="px-6 py-4 grid grid-cols-2 sm:grid-cols-4 gap-4 border-t border-gray-100">
            <div>
              <p className="text-xs text-ink-mute">CTRI No.</p>
              <p className="text-sm font-mono font-semibold text-ink mt-0.5">
                {study.ctriNo === 'PENDING'
                  ? <span className="text-danger">PENDING ⚠</span>
                  : study.ctriNo}
              </p>
            </div>
            <div>
              <p className="text-xs text-ink-mute">IEC Valid Till</p>
              <p className={clsx('text-sm font-semibold mt-0.5',
                new Date(study.iecValidTill) < new Date(Date.now() + 60*24*3600*1000) ? 'text-danger' : 'text-ink'
              )}>
                {formatDate(study.iecValidTill)}
              </p>
            </div>
            <div>
              <p className="text-xs text-ink-mute">Enrolled / Target</p>
              <p className="text-sm font-semibold text-ink mt-0.5">{study.enrolled} / {study.target} ({enrollPct}%)</p>
            </div>
            <div>
              <p className="text-xs text-ink-mute">Current Stage</p>
              <p className="text-sm font-semibold text-ink mt-0.5">Stage {study.stageNo}/10 — {study.stageName}</p>
            </div>
          </div>
        </div>

        {/* Stage Timeline */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
          <h2 className="text-sm font-semibold text-ink mb-5">Trial Lifecycle — 10-Stage Process Flow</h2>
          <StageTimeline stages={stages} currentStageNo={study.stageNo} />
        </div>

        {/* Risk Map */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
          <h2 className="text-sm font-semibold text-ink mb-4">Risk Map</h2>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-200">
                  <th className="px-4 py-3 text-left text-xs font-bold text-ink-mute uppercase tracking-wider w-1/3">Challenge</th>
                  <th className="px-4 py-3 text-left text-xs font-bold text-ink-mute uppercase tracking-wider w-1/3">Risk</th>
                  <th className="px-4 py-3 text-left text-xs font-bold text-ink-mute uppercase tracking-wider w-1/3">Mitigation</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100">
                <tr className="hover:bg-gray-50">
                  <td className="px-4 py-4 text-ink-soft">Incomplete / wrong participant data</td>
                  <td className="px-4 py-4 text-danger font-medium">Invalid records, protocol deviations</td>
                  <td className="px-4 py-4 text-ok font-medium">Mandatory eCRF validation + ABHA ID check</td>
                </tr>
                <tr className="hover:bg-gray-50">
                  <td className="px-4 py-4 text-ink-soft">IEC / CTRI approval missed</td>
                  <td className="px-4 py-4 text-danger font-medium">Illegal trial start, audit failure</td>
                  <td className="px-4 py-4 text-ok font-medium">7 Hard Gate locks modules until approval</td>
                </tr>
                <tr className="hover:bg-gray-50">
                  <td className="px-4 py-4 text-ink-soft">Data security & privacy</td>
                  <td className="px-4 py-4 text-danger font-medium">Breach, tampering, DPDP non-compliance</td>
                  <td className="px-4 py-4 text-ok font-medium">Encryption, RBAC, SHA-256 audit, India hosting</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* 3 Breakthrough Innovations */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            {
              icon: <Cpu className="w-6 h-6" />,
              color: 'info',
              title: 'CDISC Auto-Engine',
              desc: 'FDA-ready SDTM / Define-XML without third-party SAS license'
            },
            {
              icon: <Shield className="w-6 h-6" />,
              color: 'danger',
              title: 'Safety Watchtower',
              desc: '24h SAE clock + gated MedDRA / WHO-UMC sign-off'
            },
            {
              icon: <Leaf className="w-6 h-6" />,
              color: 'ayush',
              title: 'Ayush Formulation Model',
              desc: 'Polyherbal extracts, classical dosage forms (Vati, Kwatha, Churna)'
            },
          ].map(card => (
            <div key={card.title} className={clsx(
              'bg-white rounded-xl border p-5 shadow-sm hover:shadow-md transition-shadow',
              card.color === 'info'   ? 'border-info/30' :
              card.color === 'danger' ? 'border-danger/30' :
                                        'border-ayush/30'
            )}>
              <div className={clsx(
                'w-12 h-12 rounded-xl flex items-center justify-center mb-4',
                card.color === 'info'   ? 'bg-info/10 text-info' :
                card.color === 'danger' ? 'bg-danger/10 text-danger' :
                                          'bg-ayush/10 text-ayush'
              )}>
                {card.icon}
              </div>
              <h3 className="text-sm font-bold text-ink mb-2">{card.title}</h3>
              <p className="text-xs text-ink-mute leading-relaxed">{card.desc}</p>
            </div>
          ))}
        </div>

        {/* CDISC Export */}
        <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h2 className="text-sm font-semibold text-ink">Export CDISC Package</h2>
              <p className="text-xs text-ink-mute mt-1">
                Generates SDTM domains DM, AE, DS, SV + Define-XML metadata (demo)
              </p>
            </div>
            <button
              onClick={handleExportCdisc}
              disabled={exporting}
              className={clsx(
                'flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-semibold text-white transition-all',
                exporting
                  ? 'bg-gray-300 cursor-not-allowed'
                  : 'bg-brand hover:bg-brand-dark shadow-sm hover:shadow-md'
              )}
            >
              <Download className="w-4 h-4" />
              {exporting ? `Generating… ${Math.round(exportProgress)}%` : '1-Click Export CDISC'}
            </button>
          </div>
          {exporting && (
            <div className="mt-4">
              <div className="w-full bg-gray-100 rounded-full h-2">
                <div
                  className="bg-brand h-2 rounded-full transition-all duration-300"
                  style={{ width: `${exportProgress}%` }}
                />
              </div>
              <p className="text-xs text-ink-mute mt-2 text-center">
                Building SDTM → ADaM → Define-XML…
              </p>
            </div>
          )}
          <div className="mt-4 p-3 bg-gray-50 rounded-lg border border-gray-100 text-xs text-ink-mute">
            <ExternalLink className="w-3.5 h-3.5 inline mr-1" />
            CDISC SDTM v3.3 · ADaM v2.1 · Define-XML 2.1 · MedDRA v27.0 · WHO-UMC causality scale
          </div>
        </div>
      </div>

      {/* Toast */}
      {toastMsg && (
        <div className="fixed bottom-6 right-6 z-50 toast-enter">
          <div className="flex items-center gap-3 bg-ok text-white px-5 py-3 rounded-xl shadow-2xl text-sm font-medium max-w-sm">
            <CheckCircle2 className="w-5 h-5 flex-shrink-0" />
            {toastMsg}
          </div>
        </div>
      )}
    </RoleGuard>
  );
}
